#!/usr/bin/env zsh

source ~/.zshrc

if [[ $# -eq 1 ]]; then
	selected=$1
else
	selected=$(find ~/iamtienng ~/threatfabric/devops/cicd ~/threatfabric/devops/core-team ~/threatfabric/devops/currence ~/threatfabric/devops/general ~/threatfabric/devops/gitops_environment ~/threatfabric/devops/note -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]]; then
	tmux attach-session -t $selected_name
else
	tmux switch-client -t $selected_name
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
