k9s:
  cluster: devops-management-aks-cluster
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - default
  view:
    active: namespace
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
