$mod = SUPER

# Application bindings
bindd = $mod, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = $mod SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = $mod SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = $mod ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = $mod SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = $mod SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = $mod SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = $mod SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian"

# Unbind
unbind = $mod, L
unbind = $mod, code:61
unbind = $mod, ALT, code:61
unbind = $mod, TAB

# Add extra bindings
# --- Service ---
bind = $mod, R, exec, hyprctl reload
# --- Focus (vim-style) ---
bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r
# --- Layout ---
bind = $mod, slash, layoutmsg, togglesplit
bind = $mod SHIFT, slash, layoutmsg, togglesplit
bind = $mod CTRL, F,      togglefloating
bind = $mod CTRL SHIFT, F, fullscreen
# --- Workspaces ---
bind = $mod, TAB, workspace, previous
bind = $mod SHIFT, TAB, movecurrentworkspacetomonitor, +1

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = $mod, SPACE
# bindd = $mod, SPACE, Omarchy menu, exec, omarchy-menu

# Logitech MX Keys
# bind = $mod SHIFT, S, exec, omarchy-cmd-screenshot          # Print Screen Button
# bind = $mod, H, exec, voxtype record toggle                 # Dictation Button
# bind = $mod, PERIOD, exec, omarchy-launch-walker -m symbols # Emoji Button
